{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "cc580d7e-7812-45bc-9674-f8cc2df6f410",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1.5.0\n"
     ]
    }
   ],
   "source": [
    "# Import necessary libraries\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.impute import SimpleImputer\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.feature_selection import SelectKBest, f_regression\n",
    "from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score\n",
    "import joblib\n",
    "from sklearn.ensemble import VotingRegressor"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7c275dfa-b847-474d-97b8-395aaef98f09",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load the dataset using a raw string or forward slashes\n",
    "legacy_player_data = pd.read_csv(r\"C:\\Users\\grise\\Downloads\\male_players (legacy).csv\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9c5ee2d7-cddf-4f2d-8f76-b706ce3cbc1e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Display first few rows of the dataset\n",
    "print(legacy_player_data.head())\n",
    "\n",
    "# Drop columns with more than 30% missing values and irrelevant columns\n",
    "drop_threshold = 0.3 * legacy_player_data.shape[0]\n",
    "legacy_player_data = legacy_player_data.dropna(thresh=drop_threshold, axis=1)\n",
    "legacy_player_data.drop(columns=['value_eur', 'wage_eur', 'release_clause_eur', 'international_reputation'], inplace=True)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "73159984-839e-417b-835b-02b4f05716ee",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "d53741fb-a00c-42b4-994f-84df7003823b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Shape of selected features: (161583, 13)\n",
      "Selected features: ['potential', 'age', 'shooting', 'passing', 'dribbling', 'physic', 'attacking_short_passing', 'skill_long_passing', 'skill_ball_control', 'movement_reactions', 'power_shot_power', 'mentality_vision', 'mentality_composure']\n"
     ]
    }
   ],
   "source": [
    "# Select numeric columns for feature selection\n",
    "numeric_features = legacy_player_data.select_dtypes(include=np.number)\n",
    "\n",
    "# Impute missing values using mean strategy\n",
    "mean_imputer = SimpleImputer(strategy='mean')\n",
    "imputed_numeric_features = pd.DataFrame(mean_imputer.fit_transform(numeric_features), columns=numeric_features.columns, index=numeric_features.index)\n",
    "\n",
    "# Define target and features\n",
    "target_variable = imputed_numeric_features['overall']\n",
    "input_features = imputed_numeric_features.drop(columns=['overall'])\n",
    "\n",
    "# Select top 13 features using SelectKBest\n",
    "feature_selector = SelectKBest(f_regression, k=13)\n",
    "top_features = feature_selector.fit_transform(input_features, target_variable)\n",
    "selected_feature_columns = input_features.columns[feature_selector.get_support()]\n",
    "\n",
    "# Create DataFrame with selected features\n",
    "selected_features_df = pd.DataFrame(top_features, columns=selected_feature_columns, index=input_features.index)\n",
    "\n",
    "# Print the shape and selected features\n",
    "print(\"Shape of selected features:\", selected_features_df.shape)\n",
    "print(\"Selected features:\", selected_feature_columns.tolist())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "def75616-5709-4521-be44-ffbbb51e366f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<style>#sk-container-id-1 {\n",
       "  /* Definition of color scheme common for light and dark mode */\n",
       "  --sklearn-color-text: black;\n",
       "  --sklearn-color-line: gray;\n",
       "  /* Definition of color scheme for unfitted estimators */\n",
       "  --sklearn-color-unfitted-level-0: #fff5e6;\n",
       "  --sklearn-color-unfitted-level-1: #f6e4d2;\n",
       "  --sklearn-color-unfitted-level-2: #ffe0b3;\n",
       "  --sklearn-color-unfitted-level-3: chocolate;\n",
       "  /* Definition of color scheme for fitted estimators */\n",
       "  --sklearn-color-fitted-level-0: #f0f8ff;\n",
       "  --sklearn-color-fitted-level-1: #d4ebff;\n",
       "  --sklearn-color-fitted-level-2: #b3dbfd;\n",
       "  --sklearn-color-fitted-level-3: cornflowerblue;\n",
       "\n",
       "  /* Specific color for light theme */\n",
       "  --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
       "  --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, white)));\n",
       "  --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
       "  --sklearn-color-icon: #696969;\n",
       "\n",
       "  @media (prefers-color-scheme: dark) {\n",
       "    /* Redefinition of color scheme for dark theme */\n",
       "    --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
       "    --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, #111)));\n",
       "    --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
       "    --sklearn-color-icon: #878787;\n",
       "  }\n",
       "}\n",
       "\n",
       "#sk-container-id-1 {\n",
       "  color: var(--sklearn-color-text);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 pre {\n",
       "  padding: 0;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-hidden--visually {\n",
       "  border: 0;\n",
       "  clip: rect(1px 1px 1px 1px);\n",
       "  clip: rect(1px, 1px, 1px, 1px);\n",
       "  height: 1px;\n",
       "  margin: -1px;\n",
       "  overflow: hidden;\n",
       "  padding: 0;\n",
       "  position: absolute;\n",
       "  width: 1px;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-dashed-wrapped {\n",
       "  border: 1px dashed var(--sklearn-color-line);\n",
       "  margin: 0 0.4em 0.5em 0.4em;\n",
       "  box-sizing: border-box;\n",
       "  padding-bottom: 0.4em;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-container {\n",
       "  /* jupyter's `normalize.less` sets `[hidden] { display: none; }`\n",
       "     but bootstrap.min.css set `[hidden] { display: none !important; }`\n",
       "     so we also need the `!important` here to be able to override the\n",
       "     default hidden behavior on the sphinx rendered scikit-learn.org.\n",
       "     See: https://github.com/scikit-learn/scikit-learn/issues/21755 */\n",
       "  display: inline-block !important;\n",
       "  position: relative;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-text-repr-fallback {\n",
       "  display: none;\n",
       "}\n",
       "\n",
       "div.sk-parallel-item,\n",
       "div.sk-serial,\n",
       "div.sk-item {\n",
       "  /* draw centered vertical line to link estimators */\n",
       "  background-image: linear-gradient(var(--sklearn-color-text-on-default-background), var(--sklearn-color-text-on-default-background));\n",
       "  background-size: 2px 100%;\n",
       "  background-repeat: no-repeat;\n",
       "  background-position: center center;\n",
       "}\n",
       "\n",
       "/* Parallel-specific style estimator block */\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item::after {\n",
       "  content: \"\";\n",
       "  width: 100%;\n",
       "  border-bottom: 2px solid var(--sklearn-color-text-on-default-background);\n",
       "  flex-grow: 1;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel {\n",
       "  display: flex;\n",
       "  align-items: stretch;\n",
       "  justify-content: center;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  position: relative;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:first-child::after {\n",
       "  align-self: flex-end;\n",
       "  width: 50%;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:last-child::after {\n",
       "  align-self: flex-start;\n",
       "  width: 50%;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:only-child::after {\n",
       "  width: 0;\n",
       "}\n",
       "\n",
       "/* Serial-specific style estimator block */\n",
       "\n",
       "#sk-container-id-1 div.sk-serial {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "  align-items: center;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  padding-right: 1em;\n",
       "  padding-left: 1em;\n",
       "}\n",
       "\n",
       "\n",
       "/* Toggleable style: style used for estimator/Pipeline/ColumnTransformer box that is\n",
       "clickable and can be expanded/collapsed.\n",
       "- Pipeline and ColumnTransformer use this feature and define the default style\n",
       "- Estimators will overwrite some part of the style using the `sk-estimator` class\n",
       "*/\n",
       "\n",
       "/* Pipeline and ColumnTransformer style (default) */\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable {\n",
       "  /* Default theme specific background. It is overwritten whether we have a\n",
       "  specific estimator or a Pipeline/ColumnTransformer */\n",
       "  background-color: var(--sklearn-color-background);\n",
       "}\n",
       "\n",
       "/* Toggleable label */\n",
       "#sk-container-id-1 label.sk-toggleable__label {\n",
       "  cursor: pointer;\n",
       "  display: block;\n",
       "  width: 100%;\n",
       "  margin-bottom: 0;\n",
       "  padding: 0.5em;\n",
       "  box-sizing: border-box;\n",
       "  text-align: center;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 label.sk-toggleable__label-arrow:before {\n",
       "  /* Arrow on the left of the label */\n",
       "  content: \"▸\";\n",
       "  float: left;\n",
       "  margin-right: 0.25em;\n",
       "  color: var(--sklearn-color-icon);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {\n",
       "  color: var(--sklearn-color-text);\n",
       "}\n",
       "\n",
       "/* Toggleable content - dropdown */\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content {\n",
       "  max-height: 0;\n",
       "  max-width: 0;\n",
       "  overflow: hidden;\n",
       "  text-align: left;\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content.fitted {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content pre {\n",
       "  margin: 0.2em;\n",
       "  border-radius: 0.25em;\n",
       "  color: var(--sklearn-color-text);\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content.fitted pre {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {\n",
       "  /* Expand drop-down */\n",
       "  max-height: 200px;\n",
       "  max-width: 100%;\n",
       "  overflow: auto;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {\n",
       "  content: \"▾\";\n",
       "}\n",
       "\n",
       "/* Pipeline/ColumnTransformer-specific style */\n",
       "\n",
       "#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Estimator-specific style */\n",
       "\n",
       "/* Colorize estimator box */\n",
       "#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label label.sk-toggleable__label,\n",
       "#sk-container-id-1 div.sk-label label {\n",
       "  /* The background is the default theme color */\n",
       "  color: var(--sklearn-color-text-on-default-background);\n",
       "}\n",
       "\n",
       "/* On hover, darken the color of the background */\n",
       "#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "/* Label box, darken color on hover, fitted */\n",
       "#sk-container-id-1 div.sk-label.fitted:hover label.sk-toggleable__label.fitted {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Estimator label */\n",
       "\n",
       "#sk-container-id-1 div.sk-label label {\n",
       "  font-family: monospace;\n",
       "  font-weight: bold;\n",
       "  display: inline-block;\n",
       "  line-height: 1.2em;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label-container {\n",
       "  text-align: center;\n",
       "}\n",
       "\n",
       "/* Estimator-specific */\n",
       "#sk-container-id-1 div.sk-estimator {\n",
       "  font-family: monospace;\n",
       "  border: 1px dotted var(--sklearn-color-border-box);\n",
       "  border-radius: 0.25em;\n",
       "  box-sizing: border-box;\n",
       "  margin-bottom: 0.5em;\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "/* on hover */\n",
       "#sk-container-id-1 div.sk-estimator:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Specification for estimator info (e.g. \"i\" and \"?\") */\n",
       "\n",
       "/* Common style for \"i\" and \"?\" */\n",
       "\n",
       ".sk-estimator-doc-link,\n",
       "a:link.sk-estimator-doc-link,\n",
       "a:visited.sk-estimator-doc-link {\n",
       "  float: right;\n",
       "  font-size: smaller;\n",
       "  line-height: 1em;\n",
       "  font-family: monospace;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  border-radius: 1em;\n",
       "  height: 1em;\n",
       "  width: 1em;\n",
       "  text-decoration: none !important;\n",
       "  margin-left: 1ex;\n",
       "  /* unfitted */\n",
       "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-unfitted-level-1);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link.fitted,\n",
       "a:link.sk-estimator-doc-link.fitted,\n",
       "a:visited.sk-estimator-doc-link.fitted {\n",
       "  /* fitted */\n",
       "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-fitted-level-1);\n",
       "}\n",
       "\n",
       "/* On hover */\n",
       "div.sk-estimator:hover .sk-estimator-doc-link:hover,\n",
       ".sk-estimator-doc-link:hover,\n",
       "div.sk-label-container:hover .sk-estimator-doc-link:hover,\n",
       ".sk-estimator-doc-link:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "div.sk-estimator.fitted:hover .sk-estimator-doc-link.fitted:hover,\n",
       ".sk-estimator-doc-link.fitted:hover,\n",
       "div.sk-label-container:hover .sk-estimator-doc-link.fitted:hover,\n",
       ".sk-estimator-doc-link.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "/* Span, style for the box shown on hovering the info icon */\n",
       ".sk-estimator-doc-link span {\n",
       "  display: none;\n",
       "  z-index: 9999;\n",
       "  position: relative;\n",
       "  font-weight: normal;\n",
       "  right: .2ex;\n",
       "  padding: .5ex;\n",
       "  margin: .5ex;\n",
       "  width: min-content;\n",
       "  min-width: 20ex;\n",
       "  max-width: 50ex;\n",
       "  color: var(--sklearn-color-text);\n",
       "  box-shadow: 2pt 2pt 4pt #999;\n",
       "  /* unfitted */\n",
       "  background: var(--sklearn-color-unfitted-level-0);\n",
       "  border: .5pt solid var(--sklearn-color-unfitted-level-3);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link.fitted span {\n",
       "  /* fitted */\n",
       "  background: var(--sklearn-color-fitted-level-0);\n",
       "  border: var(--sklearn-color-fitted-level-3);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link:hover span {\n",
       "  display: block;\n",
       "}\n",
       "\n",
       "/* \"?\"-specific style due to the `<a>` HTML tag */\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link {\n",
       "  float: right;\n",
       "  font-size: 1rem;\n",
       "  line-height: 1em;\n",
       "  font-family: monospace;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  border-radius: 1rem;\n",
       "  height: 1rem;\n",
       "  width: 1rem;\n",
       "  text-decoration: none;\n",
       "  /* unfitted */\n",
       "  color: var(--sklearn-color-unfitted-level-1);\n",
       "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link.fitted {\n",
       "  /* fitted */\n",
       "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-fitted-level-1);\n",
       "}\n",
       "\n",
       "/* On hover */\n",
       "#sk-container-id-1 a.estimator_doc_link:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-3);\n",
       "}\n",
       "</style><div id=\"sk-container-id-1\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>LinearRegression()</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item\"><div class=\"sk-estimator fitted sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-1\" type=\"checkbox\" checked><label for=\"sk-estimator-id-1\" class=\"sk-toggleable__label fitted sk-toggleable__label-arrow fitted\">&nbsp;&nbsp;LinearRegression<a class=\"sk-estimator-doc-link fitted\" rel=\"noreferrer\" target=\"_blank\" href=\"https://scikit-learn.org/1.5/modules/generated/sklearn.linear_model.LinearRegression.html\">?<span>Documentation for LinearRegression</span></a><span class=\"sk-estimator-doc-link fitted\">i<span>Fitted</span></span></label><div class=\"sk-toggleable__content fitted\"><pre>LinearRegression()</pre></div> </div></div></div></div>"
      ],
      "text/plain": [
       "LinearRegression()"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Split the data into training and testing sets\n",
    "X_train, X_test, y_train, y_test = train_test_split(selected_features_df, target_variable, test_size=0.2, random_state=42)\n",
    "\n",
    "# Train Random Forest Regressor\n",
    "from sklearn.ensemble import RandomForestRegressor\n",
    "random_forest_model = RandomForestRegressor(n_estimators=100, max_depth=7, random_state=42)\n",
    "random_forest_model.fit(X_train, y_train)\n",
    "\n",
    "# Train Decision Tree Regressor\n",
    "from sklearn.tree import DecisionTreeRegressor\n",
    "decision_tree_model = DecisionTreeRegressor(max_depth=5, min_samples_split=5)\n",
    "decision_tree_model.fit(X_train, y_train)\n",
    "\n",
    "# Train Linear Regression\n",
    "from sklearn.linear_model import LinearRegression\n",
    "linear_regression_model = LinearRegression()\n",
    "linear_regression_model.fit(X_train, y_train)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "a37efef1-3105-46ad-ba0b-75cf972fef38",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "RandomForest - RMSE: 1.9739, MAE: 1.3853, R2: 0.9214\n",
      "DecisionTree - RMSE: 2.7605, MAE: 2.0483, R2: 0.8463\n",
      "LinearRegression - RMSE: 2.0756, MAE: 1.6091, R2: 0.9131\n"
     ]
    }
   ],
   "source": [
    "# Evaluate models on the test set\n",
    "trained_models = {\n",
    "    'RandomForest': random_forest_model, \n",
    "    'DecisionTree': decision_tree_model, \n",
    "    'LinearRegression': linear_regression_model\n",
    "}\n",
    "\n",
    "for model_name, model in trained_models.items():\n",
    "    y_pred = model.predict(X_test)\n",
    "    rmse = np.sqrt(mean_squared_error(y_test, y_pred))\n",
    "    mae = mean_absolute_error(y_test, y_pred)\n",
    "    r2 = r2_score(y_test, y_pred)\n",
    "    print(f\"{model_name} - RMSE: {rmse:.4f}, MAE: {mae:.4f}, R2: {r2:.4f}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "6c5389db-4689-4381-a112-7a7124f7c720",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\grise\\AppData\\Local\\Temp\\ipykernel_24324\\3144459591.py:2: DtypeWarning: Columns (25,108) have mixed types. Specify dtype option on import or set low_memory=False.\n",
      "  data_2022 = pd.read_csv(r'C:\\Users\\grise\\Downloads\\players_22.csv')\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "Index(['sofifa_id', 'overall', 'potential', 'age', 'height_cm', 'weight_kg',\n",
       "       'nationality_id', 'weak_foot', 'skill_moves',\n",
       "       'international_reputation', 'attacking_crossing', 'attacking_finishing',\n",
       "       'attacking_heading_accuracy', 'attacking_short_passing',\n",
       "       'attacking_volleys', 'skill_dribbling', 'skill_curve',\n",
       "       'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control',\n",
       "       'movement_acceleration', 'movement_sprint_speed', 'movement_agility',\n",
       "       'movement_reactions', 'movement_balance', 'power_shot_power',\n",
       "       'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots',\n",
       "       'mentality_aggression', 'mentality_interceptions',\n",
       "       'mentality_positioning', 'mentality_vision', 'mentality_penalties',\n",
       "       'mentality_composure', 'defending_marking_awareness',\n",
       "       'defending_standing_tackle', 'defending_sliding_tackle',\n",
       "       'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking',\n",
       "       'goalkeeping_positioning', 'goalkeeping_reflexes'],\n",
       "      dtype='object')"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Importing FIFA 2022 dataset\n",
    "data_2022 = pd.read_csv(r'C:\\Users\\grise\\Downloads\\players_22.csv')\n",
    "numeric_2022_data = data_2022.select_dtypes(include=[np.number]).dropna(axis=1)\n",
    "numeric_2022_data.columns\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "eda2f0ea-397d-41d0-8015-930783857a1d",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0        93\n",
       "1        92\n",
       "2        91\n",
       "3        91\n",
       "4        91\n",
       "         ..\n",
       "19234    47\n",
       "19235    47\n",
       "19236    47\n",
       "19237    47\n",
       "19238    47\n",
       "Name: overall, Length: 19239, dtype: int64"
      ]
     },
     "execution_count": 27,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "142b1833-e453-4947-bfc3-a57ecdb71581",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Updated X shape: (161583, 9)\n",
      "Updated y shape: (161583,)\n",
      "RandomForest on new season data - RMSE: 1.8260, MAE: 1.2970, R2: 0.9296\n",
      "DecisionTree on new season data - RMSE: 2.6552, MAE: 2.0325, R2: 0.8511\n",
      "LinearRegression on new season data - RMSE: 2.2115, MAE: 1.6932, R2: 0.8967\n"
     ]
    }
   ],
   "source": [
    "# Assuming you have defined selected_features_df and target_variable earlier\n",
    "\n",
    "# Ensure X and y have the same index\n",
    "common_index = selected_features_df.index.intersection(target_variable.index)\n",
    "\n",
    "# Define available_features based on your data\n",
    "#available_features = selected_features_df.columns.tolist()  # Adjust this based on your actual feature selection process\n",
    "available_features = []\n",
    "for items in selected_features_df:\n",
    "    if items in numeric_2022_data:\n",
    "        available_features.append(items)\n",
    "\n",
    "y_test_2022 = numeric_2022_data['overall']\n",
    "# Update X_train and y_train to use only the common indices\n",
    "X_train_updated = selected_features_df.loc[common_index, available_features]\n",
    "y_train_updated = target_variable.loc[common_index]\n",
    "\n",
    "print(f\"Updated X shape: {X_train_updated.shape}\")\n",
    "print(f\"Updated y shape: {y_train_updated.shape}\")\n",
    "\n",
    "# Retrain the models with the updated feature set and aligned y\n",
    "for model_name, model in trained_models.items():\n",
    "    model.fit(X_train_updated, y_train_updated)\n",
    "\n",
    "# Assuming you have defined numeric_2022_data and y_test_2022 earlier for evaluation\n",
    "\n",
    "# Prepare the test data with only the available features\n",
    "X_test_2022 = numeric_2022_data[available_features]\n",
    "\n",
    "# Now evaluate the models on the new season data\n",
    "for model_name, model in trained_models.items():\n",
    "    y_pred_2022 = model.predict(X_test_2022)\n",
    "    rmse_2022 = np.sqrt(mean_squared_error(y_test_2022, y_pred_2022))\n",
    "    mae_2022 = mean_absolute_error(y_test_2022, y_pred_2022)\n",
    "    r2_2022 = r2_score(y_test_2022, y_pred_2022)\n",
    "    print(f\"{model_name} on new season data - RMSE: {rmse_2022:.4f}, MAE: {mae_2022:.4f}, R2: {r2_2022:.4f}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 68,
   "id": "11c3c865-49c1-4929-8886-ece5b817fb4f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['potential',\n",
       " 'age',\n",
       " 'attacking_short_passing',\n",
       " 'skill_long_passing',\n",
       " 'skill_ball_control',\n",
       " 'movement_reactions',\n",
       " 'power_shot_power',\n",
       " 'mentality_vision',\n",
       " 'mentality_composure']"
      ]
     },
     "execution_count": 68,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "available_features"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 64,
   "id": "3c7de4b6-300c-42ba-9d48-414bb969679a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "X_train features: ['potential', 'age', 'shooting', 'passing', 'dribbling', 'physic', 'attacking_short_passing', 'skill_long_passing', 'skill_ball_control', 'movement_reactions', 'power_shot_power', 'mentality_vision', 'mentality_composure']\n",
      "X_test_2022 features: ['potential', 'age', 'attacking_short_passing', 'skill_long_passing', 'skill_ball_control', 'movement_reactions', 'power_shot_power', 'mentality_vision', 'mentality_composure']\n",
      "Common features: ['age', 'power_shot_power', 'skill_long_passing', 'mentality_composure', 'attacking_short_passing', 'mentality_vision', 'potential', 'movement_reactions', 'skill_ball_control']\n",
      "Ensemble Model on Validation Set:\n",
      "RMSE: 9.4208, MAE: 7.4985, R2: -0.8030\n",
      "Ensemble Model on New Season Data:\n",
      "RMSE: 1.8424, MAE: 1.3535, R2: 0.9283\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "['fifa_overall_rating_predictor.pkl']"
      ]
     },
     "execution_count": 64,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Print the features in X_train and X_test_2022\n",
    "print(\"X_train features:\", X_train.columns.tolist())\n",
    "print(\"X_test_2022 features:\", X_test_2022.columns.tolist())\n",
    "\n",
    "# Find the common features\n",
    "common_features = list(set(X_train.columns) & set(X_test_2022.columns))\n",
    "print(\"Common features:\", common_features)\n",
    "\n",
    "# Reorder and select only common features for both datasets\n",
    "X_train_aligned = X_train[common_features]\n",
    "X_test_2022_aligned = X_test_2022[common_features]\n",
    "\n",
    "\n",
    "# Retrain individual models\n",
    "random_forest_model.fit(X_train_aligned, y_train)\n",
    "decision_tree_model.fit(X_train_aligned, y_train)\n",
    "linear_regression_model.fit(X_train_aligned, y_train)\n",
    "\n",
    "# Retrain ensemble model\n",
    "ensemble_model = VotingRegressor(estimators=[\n",
    "    ('RandomForest', random_forest_model),\n",
    "    ('DecisionTree', decision_tree_model),\n",
    "    ('LinearRegression', linear_regression_model)\n",
    "])\n",
    "ensemble_model.fit(X_train_aligned, y_train)\n",
    "\n",
    "# Predict on validation set\n",
    "ensemble_predictions = ensemble_model.predict(X_test_2022_aligned)\n",
    "\n",
    "y_test = y_test[:len(ensemble_predictions)]\n",
    "\n",
    "# Evaluate ensemble model on validation set\n",
    "ensemble_rmse = np.sqrt(mean_squared_error(y_test, ensemble_predictions))\n",
    "ensemble_mae = mean_absolute_error(y_test, ensemble_predictions)\n",
    "ensemble_r2 = r2_score(y_test, ensemble_predictions)\n",
    "\n",
    "print(\"Ensemble Model on Validation Set:\")\n",
    "print(f\"RMSE: {ensemble_rmse:.4f}, MAE: {ensemble_mae:.4f}, R2: {ensemble_r2:.4f}\")\n",
    "\n",
    "# Predict on new season data\n",
    "ensemble_predictions_2022 = ensemble_model.predict(X_test_2022_aligned)\n",
    "\n",
    "ensemble_rmse_2022 = np.sqrt(mean_squared_error(y_test_2022, ensemble_predictions_2022))\n",
    "ensemble_mae_2022 = mean_absolute_error(y_test_2022, ensemble_predictions_2022)\n",
    "ensemble_r2_2022 = r2_score(y_test_2022, ensemble_predictions_2022)\n",
    "\n",
    "print(\"Ensemble Model on New Season Data:\")\n",
    "print(f\"RMSE: {ensemble_rmse_2022:.4f}, MAE: {ensemble_mae_2022:.4f}, R2: {ensemble_r2_2022:.4f}\")\n",
    "# Save the best model using joblib\n",
    "joblib.dump(ensemble_model, 'fifa_overall_rating_predictor.pkl')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "33991063-4f61-444c-a6bd-21a72538ce31",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "104683a9-3db8-4c2c-9876-a389255d3780",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define preprocessing function\n",
    "def preprocess_input_data(input_data):\n",
    "    input_df = pd.DataFrame([input_data])\n",
    "    for feature in common_columns:\n",
    "        if feature not in input_df.columns:\n",
    "            input_df[feature] = 0\n",
    "    return input_df[common_columns]\n",
    "\n",
    "# Define prediction function\n",
    "def predict_player_rating(input_data):\n",
    "    processed_input = preprocess_input_data(input_data)\n",
    "    return ensemble_model.predict(processed_input)[0]\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5365d3de-d3d6-4451-bfa5-a47f6babaf82",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Uncomment and run the following code in a Streamlit app\n",
    "\n",
    "# import streamlit as st\n",
    "\n",
    "# def main():\n",
    "#     st.title(\"FIFA Player Rating Predictor\")\n",
    "#     user_input = {\n",
    "#         'feature1': st.number_input('Feature 1'),\n",
    "#         'feature2': st.number_input('Feature 2'),\n",
    "#         # Add more features as needed\n",
    "#     }\n",
    "#     if st.button('Predict'):\n",
    "#         result = predict_player_rating(user_input)\n",
    "#         st.write(f\"Predicted Overall Rating: {result:.2f}\")\n",
    "\n",
    "# if __name__ == \"__main__\":\n",
    "#     main()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4e58d8a4-1914-4b98-9d11-5516f97b1c4b",
   "metadata": {},
   "outputs": [],
   "source": [
    "streamlit run app.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4bdef736-25d5-4e55-abb0-79c1ce0e9c9e",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7373f490-db93-4c0b-87cd-75dfe22cc1b2",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e98c1a8d-a23b-41cb-a7a5-d5350aa40900",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3ae3eaa2-add9-4e54-85d8-f100125a7b32",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "15b6aa1f-025d-44fe-93ba-6881b7cad76c",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "42702d11-1ac0-4707-bb00-4c22829ba921",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "68a44a3e-0276-4669-b4d4-eef3c9c881a5",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9028e22d-8e49-4ff9-b575-5d62d2297b2e",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "15d5da11-ea2d-4a35-9c93-cea8e67ffb69",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
